### PR TITLE
Update to latest google-maps-utils, expose heatmaps, apply clang-format

### PR DESCRIPTION
**Pull request by hansemannn**
- [x] Update to latest google-maps-utils 2.1.0
- [x] Apply .clang-format to all files
- [x] Expose `HeatmapLayer` API's
- [x] Update docs and examples to include heatmaps

### CODE REVIEW

**Comment by yozef** [comment]
Will test this out ;)

**Comment by hansemannn** [comment]
@yozef Ready to test! See the updated files in the example/ folder for reference.

**Comment by yozef** [comment]
The Melbourne Police station worked great.

I am trying to solve an issue internally on setting the weight/intensity of each point. However, the HeatMap feature is working ;)

**Comment by hansemannn** [comment]
Thanks, merging!

**Pull request merged**
